[project]
name = "g7-repository-web-food-recepi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "mq", email = "minhquang2006m@gmail.com" }]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "uvicorn>=0.53.0",
]

[project.scripts]
g7-repository-web-food-recepi = "g7_repository_web_food_recepi:main"
